apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: mario-nginx:0.0.1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '200m'
              memory: '200Mi'
            limits:
              cpu: '200m'
              memory: '200Mi'
