apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: mongo
  name: mongo
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  volumeClaimTemplates:
    - metadata:
        name: mongo-pv-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo
    spec:
      containers:
        - command:
            - mongod
            - --replSet
            - rs0
          image: mongo:3.4.1
          imagePullPolicy: IfNotPresent
          name: mongodb
          volumeMounts:
            - name: mongo-pv-storage
              mountPath: /data/db
          ports:
            - containerPort: 27017
              name: web
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: mongo-sidecar
        #ver como crear aca un replica set connection
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "app=mongo"
        # - command:
        #     - bash
        #     - /config/init.sh
        #   image: mongo:3.4.1
        #   imagePullPolicy: IfNotPresent
        #   name: init-mongo
        #   resources: {}
        #   terminationMessagePath: /dev/termination-log
        #   terminationMessagePolicy: File
        #   volumeMounts:
        #     - mountPath: /config
        #       name: config
        #     - name: mongo-pv-storage
        #       mountPath: /data/db
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        # - persistentVolumeClaim:
        #     claimName: mongo-pv-claim
        #   name: mongo-pv-storage
        - configMap:
            defaultMode: 420
            name: mongo-init
          name: config
  updateStrategy:
    type: OnDelete
status:
  replicas: 0
