apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix-deployment
  labels:
    app: ngnix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ngnix
  template:
    metadata:
      labels:
        app: ngnix
    spec:
      containers:
      - name: ngnix
        image: marionginx:0.0.22
        ports:
        - containerPort: 80
        resources:
            requests:
              cpu: "200m"
              memory: "200Mi"
            limits:
                  cpu: "200m"
                  memory: "200Mi"
              